### ISSUE TITLE
Pure mal equal implementation

### ISSUE THREAD

**Issue by dubek** [kanaka/mal#112]
After implementing a few of those hash-equality fixes, I have an idea: how about we implement `scalar-equal?` with a native implementation, and implement the generic `=` in mal itself (like we implement `not`). The mal implementation will use `sequential?`, `hash_map?`, `contains?`, `get`, `first`, `rest` (and `scalar-equal?`)  to recursively check whether the two data structures are equal.

Of course changing it now is a bit late, because `=` is already implemented natively in all languages (and few still got hash-equality wrong).

Here is the "pure" mal implementation of `=` (called here `new-equal?`):

```
(def! scalar-equal? =)

;; need the `and` macro
(load-file "../core.mal")

(def! sequential-equal?
  (fn* [a b]
    (if (scalar-equal? (count a) (count b))
      (if (scalar-equal? 0 (count a))
        true
        (if (new-equal? (first a) (first b))
          (sequential-equal? (rest a) (rest b))
          false))
    false)))

(def! hash-vals-equal?
  (fn* [a b map-keys]
    (if (scalar-equal? 0 (count map-keys))
      true
      (let* [key (first map-keys)]
        (if (and (contains? a key) (contains? b key))
          (if (new-equal? (get a key) (get b key))
            (hash-vals-equal? a b (rest map-keys))
            false)
          false)))))

(def! hash-map-equal?
  (fn* [a b]
    (if (scalar-equal? (count (keys a)) (count (keys b)))
      (hash-vals-equal? a b (keys a))
      false)))

;; This implements = in pure mal (using only scalar-equal? as native impl)
(def! new-equal?
  (fn* [a b]
    (cond
      (and (sequential? a) (sequential? b)) (sequential-equal? a b)
      (and (map? a) (map? b)) (hash-map-equal? a b)
      true (scalar-equal? a b))))
```

**Comment by kanaka** [comment]
That's a good idea and I did actually consider that. Since mal is primarily a learning tool, a strong goal of mine is to keep both the mal implementation of mal, and the other implementations of mal small. Obviously these two goals are in tension because there is actually a lot of other functionality that could actually be implemented in mal itself rather than the underlying language (for example, map can be implemented just with recursive functions), and on the flip side, the mal implementation could be smaller if things like let list processing were provided by the underlying language. Anyways, I tend to weigh on the side of keeping the mal implementation itself small. Also, some things like this are fairly intensive at runtime when they are done in mal instead of the underlying language (it might be slightly different balance if mal was a compiler rather than an interpreter). For example, the GNU make implementation could really use a native implementation for equality given how slow it already is.

However, I think this is interesting code that we shouldn't lose track of and is certainly useful when an implementation doesn't have native hash-map equality. With that in mind, I've actually moved some of the example programs in mal to the examples/ sub-directory. I think this would make a lot of sense in that directory. Also, one change I might suggest is that you could wrap much of the code in a conditional that checks if hash-map equality works (if (= {"a" 1} {"a" 1}), and if it doesn't then redefine "=" to add that functionality. This would then allow the file to be loaded and basically it would polyfill the language to add this if it doesn't already support it.

Want to send me a PR to add this to the examples directory (and maybe make the change I suggested)?

**Comment by kanaka** [comment]
I'm closing this since the pure mal version is now in the examples directory. Thanks @dubek!
