### ISSUE TITLE
Implement native hash-map compare across all implementations

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#116]
This is to track the remaining implementations that need native hash-map equality.

Here is current list of implementations which still need it native hash-map:
- [x] forth
- [x] guile
- [x] kotlin
- [x] matlab
- [x] miniMAL
- [x] ocaml
- [x] perl
- [x] r
- [x] racket
- [x] vb

@dubek, since we both seem to be working through them, let's claim them when we start working on them so that we don't duplicate work. So to start off, I'll do miniMAL.

**Comment by dubek** [comment]
I'm out of town till next week so ain't gonna advance in the need few days.
Leave some for me!

**Comment by dubek** [comment]
I'm claiming ocaml, and afterwards I'll try racket.

**Comment by dubek** [comment]
ocaml fix in #118

**Comment by dubek** [comment]
racket fix in #119 .

While coding this, I noticed another problem with implementations that rely on "native" `=` or `equal?` operator - they fail when you have nested vector/list comparisons. For example, in Racket, before the fix:

```
user> (= [1 2] (list 1 2))
true
user> (= [[1 2]] [(list 1 2)])
false
```

The first one is good (and tested in tests of step4); the second one is incorrect (and now fixed in #119 ).

So besides broken hash-map equality we also have this case. Not sure if you want to add this test case as mandatory (next to the other cases of vector/list equality in step4) or soft-fail.

**Comment by kanaka** [comment]
It should eventually be with the other vector/list tests, but to avoid breaking Travis until they are fixed, let's make it soft for now until we have most fixed.

**Comment by kanaka** [comment]
The embedded sequence implementations is tracked here: https://github.com/kanaka/mal/issues/123

**Comment by kanaka** [comment]
Just pushed a fix for R.

**Comment by dubek** [comment]
Guile fix in #124.

**Comment by kanaka** [comment]
matlab pushed.

**Comment by ivern** [comment]
@kanaka want me to fix the Kotlin implementation?

**Comment by kanaka** [comment]
@ivern that would be great.

**Comment by ivern** [comment]
I've fixed my pull request to contain a single commit.

**Comment by ivern** [comment]
Kotlin should be updated to fixed now that it's merged.

**Comment by kanaka** [comment]
I merged before the travis was finish with the PR, and unfortunately, travis doesn't pull the right thing so tests start to fail after the merge. So I'll wait for the travis builds for the merge itself to finish and verify and then close this if everything checks out.

**Comment by kanaka** [comment]
Looks good. Closing.
