### ISSUE TITLE
Question: Writing some macros for familiar lisp expressions

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#147]
Hi,

I'd like to define some familiar lisp expressions in MAL. Lisp style defun, defmacro and creating aliases of functions/macros.

How would you write macros for lisp style defun and defmacro?

Also, I was wondering how you would write defalias in MAL. 

Thanks,
Kerry

**Comment by kanaka** [comment]
You can create an alias just by doing:

```clojure
(def! new-name old-name)
```

However, note that this creates an "alias" to the value of old-name, and not to the old-name reference itself. In other words, after you create new-name, if you change what old-name points to, new-name will still point to the original value. And yes, both function and macros in mal are values (unlike many lisps where only functions are first class values).

However, the above won't work for special forms (like def!, defmacro!, fn*, let*, etc). For that you'll need to create new macros to wrap the special forms. For example, to create a Clojure style `defn` you could do something like this:

```clojure
(defmacro! defn (fn* (name args body) `(def! ~name (fn* ~args ~body))))
```

Of course, that's not must more than an alias really. If you wanted to do anything more interesting with args (such destructuring) then your macro definition would be more complicated of course. I'll leave that sort of thing up to you. If you do come up with aliases that work well to make mal more like another Lisp, feel free to send a pull requests adding a file to the `examples/` subdirectory because I think that would be interesting to other people too.
