### ISSUE TITLE
Build Rust in release mode

### ISSUE THREAD

**Issue by arthurprs** [kanaka/mal#22]
cargo build --release

This enables compiler optimizations and will likely give it a big boost without touching the code.

**Comment by kanaka** [comment]
Ah! I'm not sure how I missed that. Sure enough, that gives about 10X performance boost and places it firmly with the other AOT compiled languages (C, Go, Nim, OCaml).

Pushed 434516e

**Comment by arthurprs** [comment]
Cool! Were are you keeping the scores? It would be nice to have them in a wiki page

**Comment by kanaka** [comment]
@arthurprs well, I'm not really keeping score yet. Those stats were really just for my own personal enlightenment as a VERY rough comparison. You can of course run them all yourself (make perf or make perf^IMPL), you just need to install the dependencies for the the ones you're interested in.

I think once I have tests that are more statistically valid, then I might put up a wiki page or something. I'll still have a big caveat on it because the implementations do vary enough that comparisons will always be very approximate (as with all microbenchmarks).
