### ISSUE TITLE
Node / Js / es6 step 0

### ISSUE THREAD

**Issue by dotmilk** [kanaka/mal#258]
I've noticed the `node-gyp rebuild` fails when I `npm --install` in the js or es6 implementations.
Found out why [here](https://github.com/node-ffi/node-ffi/issues/337) had to bump ffi to 2.2.0

That is not however the issue per se. My issue is that the tests fail (I would assume unless I use the ffi readline) 

I was trying to rework it myself from scratch and started on my own implementation.

Currently I'm using the following for step 0
```
const readline = require('readline')
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
})
rl.setPrompt('user> ')

function READ(inp) {return inp}
function EVAL(inp) {return inp}
function PRINT(inp) {return inp}

function rep(inp) {
    return PRINT(EVAL(READ(inp)))
}


rl.on('line', (inp) => {
    process.stdout.write(`${inp}\n`)
    rl.prompt()
})
rl.on('close',()=>{
    process.exit()
})

rl.prompt()
```

And all tests fail like this: 

```
FAILED TEST (line 3): abcABC123 -> ['',abcABC123]:
    Expected : 'abcABC123\r\nabcABC123'
    Got      : None
```

however when i run this myself and enter input etc it works as expected. What is it that the python test is doing which prevents this from working?

**Comment by kanaka** [comment]
The node readline module has a bit of an issue properly detecting and responding to non-interactive use. In order to get it to pass the tests, you need to call createInterface using the `terminal: false` option. Note that you may want to add a command line option for this because for interactive use you will want the readline features (history, line editing, etc).

There are actually a few other implementations that have the same issue: C#, F#, VB.net, and Tcl. The way this is handled in the toplevel Makefile is by setting the RAW environment variable to 1 when calling the implementation `run` script during testing:

```
$ grep RAW Makefile
get_runtest_cmd = $(call get_run_prefix,$(1),$(2),$(if $(filter cs fsharp tcl vb,$(1)),RAW=1,)) ...
```

You can see how the `--raw` option is added in the run script:

```
$ grep "raw" */run
cs/run:exec mono $(dirname $0)/${STEP:-stepA_mal}.exe ${RAW:+--raw} "${@}"
fsharp/run:exec mono $(dirname $0)/${STEP:-stepA_mal}.exe ${RAW:+--raw} "${@}"
tcl/run:exec tclsh $(dirname $0)/${STEP:-stepA_mal}.tcl ${RAW:+--raw} "${@}"
vb/run:exec mono $(dirname $0)/${STEP:-stepA_mal}.exe ${RAW:+--raw} "${@}"
```

In case you are curious (and for others who may stumble onto this issue), here is what is happening. The runtest.py script launches the implementation using an interactive pty. Most readline/lineedit implementation detect this properly and will print readline prompt so that the test driver can determine when the implementation is ready for the next test line. However, the implementation I listed above and the readline module in node, do some non-standard way of detecting interactive and come to the conclusion that they are being used in non-interactive mode and so the readline prompt is never actually display and the runtest.py script times out waiting for it.

Hope that helps.
