### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by zaoqi** [kanaka/mal#282]

**Comment by wasamasa** [comment]
Please provide a description, otherwise we can only guess what your intent is behind this ticket.  Same goes for #283 and #284.  If I had to guess, they're about a spec (which already got a ticket in #241), extending Mal to the level of Scheme (which won't happen) or compiling Scheme/Clojure to Mal (good luck with that).

**Comment by zaoqi** [comment]
@wasamasa 
I can't find something like "The mal Reference"

**Comment by wasamasa** [comment]
That's because there isn't one yet. You can find a bit of discussion what would go into one at #241.

**Comment by kanaka** [comment]
I'm closing this since it's already covered by #241
