### ISSUE TITLE
Compile a Lisp

### ISSUE THREAD

**Issue by zaoqi** [kanaka/mal#295]
Like https://github.com/dubek/malc

**Comment by kanaka** [comment]
@zaoqi yes, @dubek is part of the core mal team. In the past we have actually discussed a sequel to the mal guide that would cover some advanced topics like compilation, interop. We've also discussed moving some parts of malc (such as the tokenizer and reader) to a "./lib" dir in mal along with some other things that are currently in "./examples".

@dubek, for now, it might be worth while to at least mention malc at the end of the current guide (or even in README intro section) so that people who might be interested in it will be more likely to find it. 

In the meantime, @zaoqi I'm going to close this issue since I'm not clear what you are asking for. We don't capture all the aspirational items in tickets. You can look in docs/TODO for some miscellaneous thoughts about fixes and features.
