### ISSUE TITLE
Can't run tests using rustyline

### ISSUE THREAD

**Issue by Roger** [kanaka/mal#313]
I'm trying to implement a rust version of mal, but I can't run the tests because of how the readline implementation of rustyline is made, it add some control codes, I tryied making a regex that removes the control codes(in runtests.py), that somehow worked, but it also get a \r at the start of the lines..

Example output for 'abcABC123':
'\r\x1b[6CabcABC123\r\nabcABC123\r\n\r\x1b[0Kuser> \r\x1b[6C'

Any idea of how to fix tests for rustyline?

**Comment by kanaka** [comment]
If rustyline is based on linenoise then I'm not too surprised that it is misbehaving since linenoise has similar issues.

Generally the way that we work around bad readline implementations is by adding a `--raw` command line option to the implementation that just does direct (non-readline) input. That way it's testable using the normal tools but still has readline friendliness. You can use the lua implementation for reference (which also uses linenoise). Look at `lua/step0_repl.lua` and `lua/readline.lua`.

**Comment by Roger** [comment]
Oh I see.. wouldn't be nice to add some reference about this on the guide or readme?

**Comment by kanaka** [comment]
@Roger I'm be happy to accept a PR that added this to the guide.
