### ISSUE TITLE
How to use it in Microsoft Excel?

### ISSUE THREAD

**Issue by zaoqi-unsafe** [kanaka/mal#329]

**Comment by wasamasa** [comment]
Since there's no existing implementation, make one. This is what this repository is about, teaching people how to *make* a Lisp. Use whatever Excel provides for scripting (VBA being the obvious option, but there's been Python plugins for Excel as well...). Maybe the existing Visual Basic implementation is of use. You may also find my https://github.com/wasamasa/mal-candidates repository useful to test how feasible it is to implement MAL in Excel.

**Comment by wasamasa** [comment]
I went over the issue tracker and found this is still open. New Excel versions have Power Query which gives you access to the functional M programming language.  This might give you a better way than VBA.  I still don't see any feasible way to test an implementation with our test rig though, so it will have to live in its own repo if that's indeed the case.
