### ISSUE TITLE
Macros don't work in second-order self-hosting

### ISSUE THREAD

**Issue by bjh21** [kanaka/mal#431]
If I run the mal implementation of mal inside itself, macros stop working (test is from `tests/step8_macros.mal`):

```
bjh21@sole:~/mal/python$ python stepA_mal.py ../mal/stepA_mal.mal ../mal/stepA_mal.mal
Mal [python-mal-mal]
nil
mal-user> (defmacro! one (fn* () 1))
{:__MAL_MACRO__ (EVAL (nth ast 2) env)}
mal-user> (one)
Uncaught exception: 'Hash_Map' object is not callable
```
The problem seems to have been introduced by #400. af49dc5b works:
```
bjh21@sole:~/mal/python$ python stepA_mal.py ../mal/stepA_mal.mal ../mal/stepA_mal.mal
Mal [python-mal-mal]
mal-user> (defmacro! one (fn* () 1))
<function fn at 0xf7919064>
mal-user> (one)
1
```
but ed9f32cd does not:
```
bjh21@sole:~/mal/python$ python stepA_mal.py ../mal/stepA_mal.mal ../mal/stepA_mal.mal
Mal [python-mal-mal]
nil
mal-user> (defmacro! one (fn* () 1))
{:__MAL_MACRO__ (EVAL (nth ast 2) env)}
mal-user> (one)
Uncaught exception: 'Hash_Map' object is not callable
```

**Comment by kanaka** [comment]
It turns out the key issue is the new _map? function. It causes issues in a few places but the biggest issue is that it breaks the `_macro?` function for the second order mal instance. The `_macro?` function contains a `(map? x)` call that returns false resulting in the `_macro?` call returning false. I'll push something later that fixes this and also that activates second order self-hosted tests so we can catch this sort of issue in the future.

**Comment by kanaka** [comment]
ff4e5f1 has a fix and also activates a couple of second-order self-host test entries.
