### ISSUE TITLE
Consider .bas extension for bbc-basic files so that LOC stats are counted

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#437]
Right now the bbc-basic implementation isn't getting counted automatically by the stats target because the modules have no extensions and the step files use an extension that isn't recognized by loccount.

@bjh21 would there be any issue standardizing the extensions to use `.bas`? Right now I have to manually update the bbc-basic data whenever I update the language graph: https://kanaka.github.io/mal/graph/

**Comment by bjh21** [comment]
There is a moderate-sized can of worms here.

First, the simple bit: I don't think changing `.bbc` to `.bas` would have any adverse consequences. I only chose `.bbc` because some bit of Brandy documentation used it, while none of Brandy's documentation used `.bas`.

For preference, I would have named all of the files without extensions, since that's what I'd do under RISC OS. However, the mal build system can't cope with that, which is why I had to add an extension to the step files.

However, I deliberately didn't add an extension to the library file names, and this is where the worms come in. RISC OS uses `.` as its directory separator, so `LIBRARY "types.bas"` means "load the file `bas` from the directory `types`. This would require a rather odd directory layout under RISC OS. I suppose this could be helped by having `tokenize,ffe` also edit the `LIBRARY` statements to convert from Unix to RISC OS file names.

Incidentally, I think on the graph the BASIC dialects should be shown as having static typing. Each BASIC variable holds a string, an integer, or a floating-point value based on its suffix (or lack thereof). We build a dynamic type system on top of that, but BASIC itself doesn't have dynamic types.

**Comment by kanaka** [comment]
You're right about the static typing for BASICs. I've update that in the graph. Don't spend too much effort solving the path extension issue. If you have an epiphany at some point then that would be great. I can manually update the bbc-basic data manually for now (although I'm sure I'll forget at some point). One option that comes to mind would be a simple build definition that does some copies to names that are runnable in RISC OS. That would enable stats counting and runtime without ugly paths. But it does mean there is a extraneous build step.

**Comment by kanaka** [comment]
Verified that this is resolved by #438. Thanks @bjh21
