### ISSUE TITLE
有人用scratch实现这个lisp了吗？

### ISSUE THREAD

**Issue by zhlisp** [kanaka/mal#498]
请问有人计划用scratch来实现这个lisp吗？

**Comment by wasamasa** [comment]
I've used Bing's translator for this, so pardon for any mistakes.

No, I doubt anyone is working on implementing MAL in Scratch. Here are some reasons:

- Scratch is a visual programming language, projects are exported to ZIP files containing JSON and who knows what else. This repo contains implementations stored as textual files. At best we'll link to your implementation, this has been done for Holy-C for example.
- An implementation submitted to this repository has to run in Travis CI under Linux, Mac or Windows. Since Scratch is a browser-based environment this is going to be hard. It's not impossible, but I have my doubts it can be done.
- What I've read about Scratch so far suggests it's hard to do anything advanced in it. There's no first-class lists even. Feel free to check out https://github.com/wasamasa/mal-candidates/ to get an idea what you need from a regular programming language.
