### ISSUE TITLE
`do` does not have to be tail recursive optimized (?)

### ISSUE THREAD

**Issue by twolodzko** [kanaka/mal#556]
Unless I'm missing something, `do` function does not have to be tail recursive optimized, as it behaves same as functions that are functions that are evaluated in a standard way. In fact, it does work same as calling something like `(last (list ...))`.

My guess is that `do` was added to the list of commands to be tail recursive optimized, because in other lisps (Scheme, Racket, Clisp) do is a loop-starting function.

Of course, if I'm missing something, I'd be grateful for a comment.

**Comment by kanaka** [comment]
To minimize stack memory consumption, any forms that are in tail position should be evaluated without creating a stack frame. If you have a do form: `(do (fn1) (fn2) (fn3))`, the evaluator function in the implementation language evaluates each of the do forms. When processing `(fn1)` and `(fn2)` the evaluator needs to keep track of the fact that there is more to process. It has to remember the additional work it needs to do. The easiest way to do this is by recursively calling into itself for the `(fn1)` and `(fn2)` forms (thus using the stack to keep track of what is still to be done). When the evaluator gets to the final `(fn3)` form, it no longer has to keep track of any remaining work (i.e. when it's processing the tail position) so it can just loop back to the beginning of it's own stack context and continue processing `(fn3)` and not consume any additional stack space. Note one downside of this is that withouth additional tracking mechanisms, a crash and stacktrace at this position would not show the `(do)` form as part of the stack.

There are other non-stack consuming ways to do evaluation rather than recursively calling into the evaluator function but they are less natural and add substantial complication for the implementors.

**Comment by twolodzko** [comment]
Thanks for the clarification!
